// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:tuas_manning_2/models/appliance.dart';
import 'package:tuas_manning_2/models/manning_record.dart';
import 'package:tuas_manning_2/models/personnel.dart';
import 'package:tuas_manning_2/models/personnel_type.dart';
import 'package:tuas_manning_2/models/rank.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ApplianceAdapter());
    registerAdapter(ManningRecordAdapter());
    registerAdapter(PersonnelAdapter());
    registerAdapter(PersonnelTypeAdapter());
    registerAdapter(PositionAdapter());
    registerAdapter(RankAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ApplianceAdapter());
    registerAdapter(ManningRecordAdapter());
    registerAdapter(PersonnelAdapter());
    registerAdapter(PersonnelTypeAdapter());
    registerAdapter(PositionAdapter());
    registerAdapter(RankAdapter());
  }
}
